### ISSUE TITLE
Can't create GalaxyPrefab with ImageDistributor

### ISSUE THREAD

**Issue by PsY4** [simeonradivoev/Galaxia#1]
Hi Simeon, 

when i select or drop a Texture in the 3 maps inputs in the inspector, noting happens ! It's not in the inputs...
same with the provided examples PNGs
even in example prefabls, i can't change the maps.

when i do "Create -> Galaxy Prefab" it logs an arror  and  a warning :  

> `NullReferenceException: Object reference not set to an instance of an object
Galaxia.GalaxyPrefab.OnEnable () (at C:/Users/Simeon/Documents/Visual Studio 2013/Projects/GalaxyGenerator/GalaxyGenerator/GalaxyPrefab.cs:76)
UnityEngine.ScriptableObject:CreateInstance()
GalaxyGeneratorEditor.ScriptableObjectUtility:CreateAsset() (at C:/Users/Simeon/Documents/Visual Studio 2013/Projects/GalaxyGenerator/GalaxyGeneratorEditor/ScriptableObjectUtility.cs:14)
GalaxyGeneratorEditor.GalaxyPrefabEditor:CreateGalaxyPrefab() (at C:/Users/Simeon/Documents/Visual Studio 2013/Projects/GalaxyGenerator/GalaxyGeneratorEditor/GalaxyPrefabEditor.cs:377)`

> `Unable to find style 'AS TextArea' in skin 'LightSkin' Layout
UnityEngine.GUIStyle:op_Implicit(String)
GalaxyGeneratorEditor.GalaxyPrefabEditor:CheckStyles() (at C:/Users/Simeon/Documents/Visual Studio 2013/Projects/GalaxyGenerator/GalaxyGeneratorEditor/GalaxyPrefabEditor.cs:87)
GalaxyGeneratorEditor.GalaxyPrefabEditor:OnGUI() (at C:/Users/Simeon/Documents/Visual Studio 2013/Projects/GalaxyGenerator/GalaxyGeneratorEditor/GalaxyPrefabEditor.cs:99)
GalaxyGeneratorEditor.GalaxyPrefabEditor:OnInspectorGUI() (at C:/Users/Simeon/Documents/Visual Studio 2013/Projects/GalaxyGenerator/GalaxyGeneratorEditor/GalaxyPrefabEditor.cs:80)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)`

- unity 2017.2.0f3
- galaxia v0.4.5.1
-  clean project,  only your asset

Please help

**Comment by simeonradivoev** [comment]
It might just be a problem with the GUI. I haven't updated it yet to unity 2017.2.

**Comment by simeonradivoev** [comment]
I fixed it. I will made a build soon and upload it to the asset store. I also included a simple Volumetric nebula rendering. Check for version v0.4.6 or up.
